// package local:cowsay;
package ts:typescript@0.1.0;

// export interface ts-system {
//   get-current-directory: func() -> string;
// }

// interface ts-system {
//   get-current-directory: func() -> string;
// }

world typescript {
  import ts:typescript-system/ts@0.1.0;
  use ts:typescript-system/ts@0.1.0.{system};

  export set-sys: func(sys: system);

  export test: func() -> string;

  export canvas: interface {

    // set-sys: func(sys: system) -> void;

    resource compiler-options {
      create: static func() -> compiler-options;
    }

    // create-program: func(options: borrow<compiler-options>) -> program;
    create-program: func(options: compiler-options) -> program;

    resource program {
    }
  }
}
