package ts:typescript@0.1.0;

interface typescript {
    use ts:typescript-system/types@0.1.0.{system};

    resource program {
      constructor(sys: system);
      concat-arguments: func() -> string;
    }
}

world root {
  import ts:typescript-system/types@0.1.0;
  export typescript;
}
