package local:cowsay;

world cowsay {
  export test: func() -> string;
  export canvas: interface {
    resource compiler-options {
      create: static func() -> compiler-options;
    }

    // create-program: func(options: borrow<compiler-options>) -> program;
    create-program: func(options: compiler-options) -> program;

    resource program {
    }
  }
}
