package local:cowsay;

world cowsay {
  export test: func() -> string;
  export canvas: interface {
    ts-version: func() -> string;
    resource compileroptions {
      constructor();
      inner: func() -> u8;
      // set_inner: func(string) -> void;
    }
    // resource bundle {
    //   constructor();
    //   kind: func() -> u8;
    // }
    node-factory: func() -> nodefactory;
    resource nodefactory {
      create-void-zero: func() -> voidexpression;
    }
    resource voidexpression {
      kind: func() -> u8;
    }
  }
}
