// https://component-model.bytecodealliance.org/design/wit.html

package local:cowsay;

world cowsay {
  export test: func() -> string;
  export canvas: interface {
    ts-version: func() -> string;

    resource compiler-options {
      constructor();
      inner: func() -> u8;
      // set_inner: func(string) -> void;
      get-always-strict: func() -> option<bool>;
      set-always-strict: func(value: option<bool>);
      set-target: func(value: option<script-target>);
    }

    create-compiler-host: func(options: compiler-options, set-parent-nodes: option<bool>) -> compiler-host;

    resource compiler-host {
      set-use-case-sensitive-file-names: func(value: bool);
      // set-get-current-directory: func(value: func() -> string);
      set-get-current-directory: func(fn: fn-get-current-directory);
      // set-get-canonical-file-name: func(value: func(string) -> string);
    }

    resource fn-get-current-directory {
      call: func() -> string;
    }

    // resource bundle {
    //   constructor();
    //   kind: func() -> u8;
    // }
    node-factory: func() -> nodefactory;
    resource nodefactory {
      create-void-zero: func() -> voidexpression;
    }
    resource voidexpression {
      // kind: func() -> u8;
      kind: func() -> syntax-kind;
    }
    // bigger becuase 371
    type syntax-kind = u16;

    type script-target = string;
  }
}
