package ts:typescript-system@0.1.0;

interface types {

    record args {
        count: u8,
        one: option<string>,
        two: option<string>,
        three: option<string>
    }

    resource system {
        constructor();
        get-arguments: func() -> list<string>;
        hello: func() -> result<string,string>;
        args: func() -> args;
        
        directory-exists: func(path: string) -> result<bool,string>;
    }
}

world root {
    import wasi:cli/environment@0.2.0;
    import wasi:filesystem/types@0.2.0;
    import wasi:filesystem/preopens@0.2.0;
    export types;
}